### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by kenmazaika** [Viviensrepo/splurty2#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by Viviensrepo** [comment]
Thanks so much Ken for reviewing and giving me this useful suggestion.  

Already updated the app with the following Bootstrap mobile meta tag added to the <head> section:

<meta name="viewport" content="width=device-width, initial-scale=1">

Many thanks again also for delivering such an excellent Office Hour this week together with Marco. 

Really appreciate the guidance and support from both of you!

**Comment by Viviensrepo** [comment]
Thanks so much Ken for reviewing and giving me this useful suggestion.

Already updated the app with the following Bootstrap mobile meta tag added to the section:

\<meta name="viewport" content="width=device-width, initial-scale=1">

Many thanks again also for delivering such an excellent Office Hour this week together with Marco.

Really appreciate the guidance and support from both of you!

**Comment by kenmazaika** [comment]
Thumbs up, Vivien.  Looks like you solved the issue.

Keep up the awesome work coding! :)
